# Generated by Django 3.2.6 on 2021-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_age', models.IntegerField()),
                ('emp_location', models.CharField(max_length=20)),
            ],
        ),
    ]
