# Generated by Django 3.2.6 on 2021-08-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='emp_id',
            new_name='emp_roll',
        ),
    ]
